version: "1"
services:
  node:
    image: ghcr.io/${GITHUB_REPOSITORY}:main
    extra_hosts:
      - "supabase-personal.raspberrypi.home:192.168.1.248"
    command: "npm run start:prod"
    working_dir: /home/node/personalsysbackend
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - FTP_HOST=${FTP_HOST}
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
      - FTP_CLIENT_IMAGE_PATH=${FTP_CLIENT_IMAGE_PATH}
      - FTP_PARTNERSHIP_LOGO_PATH=${FTP_PARTNERSHIP_LOGO_PATH}
      - FTP_VIDEO_PATH=${FTP_VIDEO_PATH}
      - FTP_IMAGE_PATH=${FTP_IMAGE_PATH}
      - FTP_THUMBNAIL_PATH=${FTP_THUMBNAIL_PATH}
      - VIDEO_BASE_PATH=${VIDEO_BASE_PATH}
      - IMAGE_BASE_PATH=${IMAGE_BASE_PATH}
      - THUMBNAIL_BASE_PATH=${THUMBNAIL_BASE_PATH}
      - CLIENT_IMAGE_BASE_PATH=${CLIENT_IMAGE_BASE_PATH}
      - PARTNERSHIP_LOGO_BASE_PATH=${PARTNERSHIP_LOGO_BASE_PATH}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
    expose:
      - "3001"
    ports:
      - "3001:3001"